### ISSUE TITLE
Improve Rate Limit

### ISSUE THREAD

**Issue by cucco-io** [xxLovy/IBSLover#8]
Currently rate limit is done using redis server as a counter and count requests from every IP, there are better ways to do this, for example:

Cloudflare solutions: https://www.cloudflare.com/application-services/solutions/#protect-websites-applications-solutions
and/or
express rate limit middle ware: https://www.npmjs.com/package/express-rate-limit

**Comment by xxLovy** [comment]
Thanks!

I've updated the rate limiting functionality in our application. Now, we have implemented rate limiting directly using the express-rate-limit middleware.

The express-rate-limit middleware is configured to return a 429 status code when a user exceeds the number of allowed requests within a set time window, which aligns with the behavior we had in place with Redis.
